"""TX fields updated

Revision ID: d9aa95dbc6f1
Revises: d5bdcfec3fb1
Create Date: 2025-06-24 15:19:05.929239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9aa95dbc6f1'
down_revision: Union[str, None] = 'd5bdcfec3fb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('qty', sa.Numeric(precision=20, scale=8), nullable=False))
    op.add_column('transactions', sa.Column('value', sa.Numeric(precision=20, scale=2), nullable=False))
    op.drop_column('transactions', 'amount')
    op.drop_column('transactions', 'price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('price', sa.NUMERIC(precision=20, scale=2), autoincrement=False, nullable=False))
    op.add_column('transactions', sa.Column('amount', sa.NUMERIC(precision=20, scale=8), autoincrement=False, nullable=False))
    op.drop_column('transactions', 'value')
    op.drop_column('transactions', 'qty')
    # ### end Alembic commands ###
